library(tidyverse)

touringplans_metadata <- read_csv("data-raw/touringplans_metadata.csv",
              col_types = cols(
                DATE = col_date(format = "%m/%d/%Y"),
                WDW_TICKET_SEASON = col_character(),
                DAYOFWEEK = col_double(),
                DAYOFYEAR = col_double(),
                WEEKOFYEAR = col_double(),
                MONTHOFYEAR = col_double(),
                YEAR = col_double(),
                SEASON = col_character(),
                HOLIDAYPX = col_double(),
                HOLIDAYM = col_double(),
                HOLIDAYN = col_character(),
                HOLIDAY = col_double(),
                WDWTICKETSEASON = col_character(),
                WDWRaceN = col_character(),
                WDWeventN = col_character(),
                WDWevent = col_double(),
                WDWrace = col_double(),
                WDWSEASON = col_character(),
                WDWMAXTEMP = col_double(),
                WDWMINTEMP = col_double(),
                WDWMEANTEMP = col_double(),
                MKeventN = col_character(),
                MKevent = col_double(),
                EPeventN = col_character(),
                EPevent = col_double(),
                HSeventN = col_character(),
                HSevent = col_double(),
                AKeventN = col_character(),
                AKevent = col_double(),
                HOLIDAYJ = col_character(),
                inSession = col_character(),
                inSession_Enrollment = col_character(),
                inSession_wdw = col_character(),
                inSession_dlr = col_character(),
                inSession_sqrt_WDW = col_character(),
                inSession_sqrt_DLR = col_character(),
                inSession_California = col_character(),
                inSession_DC = col_character(),
                inSession_Central_FL = col_character(),
                inSession_Drive1_FL = col_character(),
                inSession_Drive2_FL = col_character(),
                inSession_Drive_CA = col_character(),
                inSession_Florida = col_character(),
                inSession_Mardi_Gras = col_character(),
                inSession_Midwest = col_character(),
                inSession_NY_NJ = col_character(),
                inSession_NY_NJ_PA = col_character(),
                inSession_New_England = col_character(),
                inSession_New_Jersey = col_character(),
                inSession_Nothwest = col_character(),
                INSESSION_PLANES = col_character(),
                inSession_SoCal = col_character(),
                inSession_Southwest = col_character(),
                MKEMHMORN = col_double(),
                MKEMHMYEST = col_double(),
                MKEMHMTOM = col_double(),
                MKEMHEVE = col_double(),
                MKHOURSEMH = col_double(),
                MKHOURSEMHYEST = col_double(),
                MKHOURSEMHTOM = col_double(),
                MKEMHEYEST = col_double(),
                MKEMHETOM = col_double(),
                EPEMHMORN = col_double(),
                EPEMHMYEST = col_double(),
                EPEMHMTOM = col_double(),
                EPEMHEVE = col_double(),
                EPEMHEYEST = col_double(),
                EPEMHETOM = col_double(),
                EPHOURSEMH = col_double(),
                EPHOURSEMHYEST = col_double(),
                EPHOURSEMHTOM = col_double(),
                HSEMHMORN = col_double(),
                HSEMHMYEST = col_double(),
                HSEMHMTOM = col_double(),
                HSEMHEVE = col_double(),
                HSEMHEYEST = col_double(),
                HSEMHETOM = col_double(),
                HSHOURSEMH = col_double(),
                HSHOURSEMHYEST = col_double(),
                HSHOURSEMHTOM = col_double(),
                AKEMHMORN = col_double(),
                AKEMHMYEST = col_double(),
                AKEMHMTOM = col_double(),
                AKEMHEVE = col_double(),
                AKEMHEYEST = col_double(),
                AKEMHETOM = col_double(),
                AKHOURSEMH = col_double(),
                AKHOURSEMHYEST = col_double(),
                AKHOURSEMHTOM = col_double(),
                MKOPEN = col_time(format = ""),
                MKCLOSE = col_time(format = ""),
                MKHOURS = col_double(),
                MKEMHOPEN = col_time(format = ""),
                MKEMHCLOSE = col_time(format = ""),
                MKOPENYEST = col_time(format = ""),
                MKCLOSEYEST = col_time(format = ""),
                MKHOURSYEST = col_double(),
                MKOPENTOM = col_time(format = ""),
                MKCLOSETOM = col_time(format = ""),
                MKHOURSTOM = col_double(),
                EPOPEN = col_time(format = ""),
                EPCLOSE = col_time(format = ""),
                EPHOURS = col_double(),
                EPEMHOPEN = col_time(format = ""),
                EPEMHCLOSE = col_time(format = ""),
                EPOPENYEST = col_time(format = ""),
                EPCLOSEYEST = col_time(format = ""),
                EPHOURSYEST = col_double(),
                EPOPENTOM = col_time(format = ""),
                EPCLOSETOM = col_time(format = ""),
                EPHOURSTOM = col_double(),
                HSOPEN = col_time(format = ""),
                HSCLOSE = col_time(format = ""),
                HSHOURS = col_double(),
                HSEMHOPEN = col_time(format = ""),
                HSEMHCLOSE = col_time(format = ""),
                HSOPENYEST = col_time(format = ""),
                HSCLOSEYEST = col_time(format = ""),
                HSHOURSYEST = col_double(),
                HSOPENTOM = col_time(format = ""),
                HSCLOSETOM = col_time(format = ""),
                HSHOURSTOM = col_double(),
                AKOPEN = col_time(format = ""),
                AKCLOSE = col_time(format = ""),
                AKHOURS = col_double(),
                AKEMHOPEN = col_time(format = ""),
                AKEMHCLOSE = col_time(format = ""),
                AKOPENYEST = col_time(format = ""),
                AKCLOSEYEST = col_time(format = ""),
                AKHOURSYEST = col_double(),
                AKOPENTOM = col_time(format = ""),
                AKCLOSETOM = col_time(format = ""),
                AKHOURSTOM = col_double(),
                WEATHER_WDWHIGH = col_double(),
                WEATHER_WDWLOW = col_double(),
                WEATHER_WDWPRECIP = col_double(),
                CapacityLost_MK = col_double(),
                CapacityLost_EP = col_double(),
                CapacityLost_HS = col_double(),
                CapacityLost_AK = col_double(),
                CapacityLostWGT_MK = col_double(),
                CapacityLostWGT_EP = col_double(),
                CapacityLostWGT_HS = col_double(),
                CapacityLostWGT_AK = col_double(),
                MKPRDDAY = col_double(),
                MKPRDDT1 = col_time(format = ""),
                MKPRDDT2 = col_time(format = ""),
                MKPRDDN = col_character(),
                MKPRDNGT = col_double(),
                MKPRDNT1 = col_time(format = ""),
                MKPRDNT2 = col_time(format = ""),
                MKPRDNN = col_character(),
                MKFIREWK = col_double(),
                MKFIRET1 = col_time(format = ""),
                MKFIRET2 = col_time(format = ""),
                MKFIREN = col_character(),
                EPFIREWK = col_double(),
                EPFIRET1 = col_time(format = ""),
                EPFIRET2 = col_time(format = ""),
                EPFIREN = col_character(),
                HSPRDDAY = col_double(),
                HSPRDDT1 = col_logical(),
                HSPRDDN = col_logical(),
                HSFIREWK = col_double(),
                HSFIRET1 = col_time(format = ""),
                HSFIRET2 = col_time(format = ""),
                HSFIREN = col_character(),
                HSSHWNGT = col_double(),
                HSSHWNT1 = col_time(format = ""),
                HSSHWNT2 = col_time(format = ""),
                HSSHWNN = col_character(),
                HSFIREWKS = col_double(),
                AKPRDDAY = col_double(),
                AKPRDDT1 = col_logical(),
                AKPRDDT2 = col_logical(),
                AKPRDDN = col_logical(),
                AKFIREN = col_logical(),
                AKSHWNGT = col_double(),
                AKSHWNT1 = col_time(format = ""),
                AKSHWNT2 = col_time(format = ""),
                AKSHWNN = col_character()
              )
)

names(touringplans_metadata) <- tolower(names(touringplans_metadata))
## print data dictionary for documentation
dd <- read_csv("data-raw/meta-datadictionary.csv",
               col_names = c("cat", "var", "desc", "format"))
fix_quote <- function(x) gsub("'", "\\\\'", x)
clipr::write_clip(
  glue::glue_data(x, "#'   \\item{<tolower(var)>}{<fix_quote(desc)>, <format>}",
                  .open = "<", .close = ">")
)
usethis::use_data(touringplans_metadata, overwrite = TRUE)
